server.port: 8080
discovery:
  port: 8080
  api: /api/registry
node:
  hashKey: xyz
---
spring:
  profiles: local
server.port: 8081
discovery:
  server: localhost
  address: http://${server}:${port}${api}

---
spring:
  profiles: docker
discovery:
  server: discovery
  address: http://${server}:${port}${api}
